### ISSUE TITLE
Where can I download the four datasets?

### ISSUE THREAD

**Issue by zhangruiouc** [Echo-Ji/ST-SSL#7]
Hello, where can I download the four datasets including NYCBike1, I want to download the datasets from the relevant links of STResNet and STDN, but the relevant links are not working.

**Comment by Echo-Ji** [comment]
Hi, sorry for the late reply.

You can download the raw datasets here: #9

**Comment by zhangruiouc** [comment]
Thanks for your reply! I am trying to apply your idea of spatial-temporal heterogeneity of the ST-SSL model to the prediction of catch fish in the fishing area, and I would appreciate it if you could release the code for the processing raw dataset!  I heard from your homepage that you have graduated your PhD this year, so I wish you a happy graduation and a bright future!

**Comment by zhangruiouc** [comment]
Hello, I have checked the adj_mx.npz file in the dataset. This matrix is a real symmetric matrix. For example, if the values of matrix points at positions [2,3] and [3,2] are 1, does it mean that there is a traffic correlation between region 3 and region 2? If there is a correlation in traffic flow between Region 3 and Region 2, how was this correlation obtained?
![image](https://github.com/Echo-Ji/ST-SSL/assets/130215873/1945c0f6-7a08-45ad-9c78-73cf8527056e)

**Comment by Echo-Ji** [comment]
Actually you only see part of the data of the adjacency matrix. Usually, a region is connected to the 8 surrounding regions in a grid dataset, so each row of the adjacency matrix has 8 positions that are 1.0. This also implies our data processing method as follows.

The public datasets used in our paper are all constructed on a grid basis. To transform the grid-based public datasets into graph-based data, we construct a traffic flow graph, where a node in the graph is a region in the grid data and there exists an edge between two regions if they are adjacent. The item of the adjacency matrix $a_{mn} = 1$ if there is an edge between region $r_m$ and $r_n$, otherwise $a_{mn} = 0$.

**Comment by Echo-Ji** [comment]
> Thanks for your reply! I am trying to apply your idea of spatial-temporal heterogeneity of the ST-SSL model to the prediction of catch fish in the fishing area, and I would appreciate it if you could release the code for the processing raw dataset! I heard from your homepage that you have graduated your PhD this year, so I wish you a happy graduation and a bright future!

You can refer to our [new branch](https://github.com/Echo-Ji/ST-SSL/tree/feature/data-preprocessing) for the code of data preprocessing!
